name: Firmware ErrorCheck

on:
  push:
    branches: [master, variants]
    paths:
      - ".github/workflows/firmware_error_check.yml"
      - "firmware/scripts/check_hardcoded_versions.rb"
      - "firmware/scripts/check_project_ids.rb"
      - "firmware/scripts/build_all.rb"
      - "firmware/Makefile"
      - "firmware/src/**"

  pull_request:
    branches: [master, variants]
    types: [opened, synchronize]
    paths:
      - "firmware/Makefile"
      - "firmware/src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - name: Install Dependencies
        run: sudo apt install gcc-avr avr-libc binutils-avr

      - name: Check Hardcoded Versions
        run: ruby scripts/check_hardcoded_versions.rb
        working-directory: "./firmware"

      - name: Check Project IDs
        run: ruby scripts/check_project_ids.rb --abortOnError
        working-directory: "./firmware"

      - name: Check Firmware Build Errors
        run: ruby scripts/build_all.rb --abortOnError
        working-directory: "./firmware"
