name: Firmware Deployment

on:
  push:
    branches: [variants, variants-dev]
    paths:
      - ".github/workflows/firmware_deployment.yml"
      - "firmware/ci/**/*.ts"
      - "firmware/Makefile"
      - "firmware/workers/*.mk"
      - "firmware/src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt install gcc-avr avr-libc binutils-avr

      - name: install arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: "10-2020-q4"

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: ./firmware/ci

      - name: Checkout store repo
        uses: actions/checkout@v2
        with:
          repository: yahiro07/KermiteResourceStore
          path: "./firmware/KRS"
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Check Project IDs
        run: yarn checkProjectIds --abortOnError
        working-directory: ./firmware/ci

      - name: Update All Project Distributions
        run: yarn updateAllProjectDistributions
        working-directory: ./firmware/ci

      - name: Push resources to KermiteResourceStore
        uses: cpina/github-action-push-to-another-repository@master
        if: github.ref == 'refs/heads/variants'
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "./firmware/KRS"
          destination-github-username: "github-actions[bot]"
          destination-repository-username: "yahiro07"
          destination-repository-name: "KermiteResourceStore"
          target-branch: "master"
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
          commit-message: "resources updated in github actions"
