name: Firmware Deployment

on:
  push:
    branches: [master, variants]
    paths:
      - ".github/workflows/firmware_deployment.yml"
      - "firmware/scripts/update_all_project_distributions.rb"
      - "firmware/scripts/check_breed_ids.rb"
      - "firmware/Makefile"
      - "firmware/src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - name: Install Dependencies
        run: sudo apt install gcc-avr avr-libc binutils-avr

      - name: Checkout store repo
        uses: actions/checkout@v2
        with:
          repository: yahiro07/KermiteResourceStore
          path: "./firmware/KRS"

      - name: Check Breed IDs
        run: ruby scripts/check_breed_ids.rb --abortOnError
        working-directory: "./firmware"

      - run: ruby scripts/update_all_project_distributions.rb
        working-directory: "./firmware"

      - name: Push resources to store repo
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "./firmware/KRS"
          destination-github-username: "yahiro07"
          destination-repository-name: "KermiteResourceStore"
          target-branch: "master"
          user-email: yahiro07@users.noreply.github.com
