name: Firmware ErrorCheck 2

on:
  push:
    branches: [master, variants]
    paths:
      - ".github/workflows/firmwareErrorCheck2.yml"
      - "firmware/scripts2/**/*.ts"
      - "firmware/Makefile"
      - "firmware/src/**"

  pull_request:
    branches: [master, variants]
    types: [opened, synchronize]
    paths:
      - "firmware/Makefile"
      - "firmware/src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

       - uses: bahmutov/npm-install@v1
        with:
          working-directory: ./firmware/scripts2

      - run: yarn checkHardcodedVersions
        working-directory: ./firmware/scripts2