name: CI for kermite_software

on:
  push:
    branches: [master, "cidev/**"]
    paths:
      - ".github/workflows/**"
      - "kermite_software/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      # - run: node -v
      - run: yarn install
        working-directory: kermite_software
      # - uses: bahmutov/npm-install@HEAD
      #   with:
      #     working-directory: kermite_software
      # - run: yarn lint
      #   working-directory: kermite_software
