name: CI for kermite_software

on:
  push:
    branches: [master]
    paths:
      - "kermite_software/src/**"

  pull_request:
    types: [opened, synchronize]
    branches: [master]
    paths:
      - "kermite_software/src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install Dependencies
        run: sudo apt install libusb-1.0-0 libusb-1.0-0-dev libudev-dev
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: kermite_software
      - run: yarn lint
        working-directory: kermite_software
