name: Software CI

on:
  push:
    branches: [master, develop]
    paths:
      - ".github/workflows/software_ci.yml"
      - "software/src/**"

  pull_request:
    types: [opened, synchronize]
    branches: [master, develop]
    paths:
      - "software/src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: update apt
        run: sudo apt-get update

      - name: Install Dependencies
        run: sudo apt-get install libusb-1.0-0 libusb-1.0-0-dev libudev-dev
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: software
      - run: yarn lint
        working-directory: software
